### PR TITLE
Fix single argument functions

### LINKED ISSUE #53: Fix single argument functions
Remove parentheses around single argument arrow functions

### PR DESCRIPTION
**Pull request by jn-lp**
Closes: https://github.com/metarhia/metalog/issues/53
PR-URL: #58

### CODE REVIEW

**Comment by tshemsedinov** [comment]
Add to commit message:
`Closes: https://github.com/metarhia/metalog/issues/53`
See example here for example: https://github.com/metarhia/metalog/commit/d1378390cebbdd1cc6f346856bb27184af53ff96

**Comment by jn-lp** [comment]
done ✅

**Comment by tshemsedinov** [comment]
Don't use merge commits, if you have conflicts with master you can use `git rebase master` @jn-lp, please fix this in this branch and PR, don't open new one

**Comment by tshemsedinov** [comment]
Closed in favor of https://github.com/metarhia/metalog/pull/63

**Pull request closed without merging**
