### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tshemsedinov**

### CODE REVIEW

**Comment by tshemsedinov** [comment]
@lundibundi tests failed after update to new metatests version, I can't find a problem quickly.

**Comment by lundibundi** [comment]
In the new version the `metatests` wait for the process to properly finish contrary to forcefully closing the process as it did before. The loggers after the creation initiate a `reopenTimeout` which is only removed unpon proper `close`. Therefore due to the fact that few of the loggers created in the tests are never properly `close`d (supposedly `logger1`, `logger2`, `logger5`) they will keep the process alive.
`metatests` will actually exit after `exitTimeout * 5000` millis. You can change package.json to
`"test": "metatests --exit-timeout 1 test/"` to see the error quicker.

**Comment by tshemsedinov** [comment]
@lundibundi thanks, now it works

**Comment by tshemsedinov** [comment]
Landed in https://github.com/metarhia/metalog/commit/7e63282e0dd91788a2c2c651220a9b266313fb04

**Pull request closed without merging**
